import { useState, useEffect } from "react";
import { loadData, saveData } from "./storage.js";
import data from "./data.json";

const C = { blue: "#005eb8", dk: "#060a10", card: "#0d1117", border: "rgba(255,255,255,0.06)", w: "#f1f5f9", dim: "#64748b", acc: "#3b9dff", gold: "#f59e0b", grn: "#10b981", red: "#ef4444", wGold: "#fbbf24", purp: "#a78bfa" };
const USERS = ["Tony", "Benny", "Jordy"];
const F = "'Barlow Condensed', sans-serif";

// ── THIS WEEK — generated by scripts/generate.js (real NRL fixture + Kennel scrape + Claude) ──
const MATCH = data.match;

// ── TIPPING — one option for losing, four for winning by margin ──
const TIPS = [
  { id: "loss", short: "Lose", label: "Dogs lose", emoji: "💀", color: C.red },
  { id: "win_1_6", short: "1–6", label: "Dogs by 1–6", emoji: "🐶", color: C.grn },
  { id: "win_7_12", short: "7–12", label: "Dogs by 7–12", emoji: "🐶🔥", color: C.grn },
  { id: "win_13_18", short: "13–18", label: "Dogs by 13–18", emoji: "🐶💪", color: C.grn },
  { id: "win_19_plus", short: "19+", label: "Dogs by 19+", emoji: "🐶👑", color: C.grn },
];

// ── TIP HELPER — odds + Kennel chatter (drivers were dropped — felt like filler) ──
const ODDS = data.odds;
const KENNEL_TIP_QUOTES = data.kennelTipQuotes;
const KENNEL_TIP_LEAN = data.kennelTipLean;

// ── HOT DEBATES — framed as coaching decisions, sourced from Kennel chatter ──
const DEBATES = data.debates;

// ── TRIVIA — one Bulldogs question per round, graded immediately on lock ──
const TRIVIA = data.trivia;

// ── RECAP — two questions about last week's match, sourced from real match data
//    (try scorers, top performers, key stats). Self-graded on lock. ──
const RECAPS = data.recap || [];

// ── WASHUP — generated weekly from previous match + Kennel post-match scrape ──
const WASHUP = data.washup;

// External link helper. target="_blank" is ignored by some mobile in-app browsers
// (notably WhatsApp's webview), so we also explicitly window.open on click. This is
// the most reliable way to force a new tab/window across desktop, Safari, and webviews.
function ExtLink({ href, children, style, ...rest }) {
  if (!href || href === "#") return <div style={style} {...rest}>{children}</div>;
  const handle = (e) => {
    e.preventDefault();
    e.stopPropagation();
    window.open(href, "_blank", "noopener,noreferrer");
  };
  return <a href={href} target="_blank" rel="noopener noreferrer" onClick={handle} style={style} {...rest}>{children}</a>;
}

// ── COMPONENTS ──
function relativeTime(iso) {
  if (!iso) return null;
  const ms = Date.now() - new Date(iso).getTime();
  const mins = Math.round(ms / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.round(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.round(hrs / 24);
  return `${days}d ago`;
}

// Refresh button. Two behaviours depending on identity:
//   - Tony: triggers the server-side pipeline regen (`npm run generate && build`),
//     polls /api/regenerate/status every 2s, hard-reloads when done. Takes ~60-90s.
//   - Everyone else: cache-busted reload of the current bundle. Useful when a
//     cron-driven deploy has landed and they want the new data now.
function RefreshButton({ me }) {
  const [phase, setPhase] = useState("idle"); // idle | regen | reload
  const updated = relativeTime(data.generatedAt);
  const isAdmin = me === "Tony";

  const reloadFresh = () => {
    window.location.href = window.location.pathname + "?_=" + Date.now();
  };

  const click = async () => {
    if (phase !== "idle") return;
    if (!isAdmin) {
      setPhase("reload");
      setTimeout(reloadFresh, 500);
      return;
    }
    setPhase("regen");
    try {
      const r = await fetch("/api/regenerate", {
        method: "POST",
        headers: { "x-dogs-user": me },
      });
      if (!r.ok) throw new Error(`regen failed: ${r.status}`);
    } catch (e) {
      console.error(e);
      alert("Refresh failed to start — check the server logs.");
      setPhase("idle");
      return;
    }
    // Poll until the job clears `running`. Cap the wait so a stuck job
    // doesn't spin forever — server logs are the diagnostic source if so.
    const start = Date.now();
    const tick = async () => {
      try {
        const r = await fetch("/api/regenerate/status");
        const s = await r.json();
        if (!s.running) {
          if (s.error) {
            alert(`Refresh failed: ${s.error}. Check Railway logs.`);
            setPhase("idle");
            return;
          }
          reloadFresh();
          return;
        }
      } catch (e) { /* network blip — keep polling */ }
      if (Date.now() - start > 180000) { // 3min cap
        alert("Refresh is taking longer than expected. Try again in a minute.");
        setPhase("idle");
        return;
      }
      setTimeout(tick, 2000);
    };
    setTimeout(tick, 2000);
  };

  const spinning = phase !== "idle";
  const title = phase === "regen"
    ? "Refreshing data — about a minute…"
    : (updated ? `Updated ${updated} — tap to refresh${isAdmin ? " (re-runs pipeline)" : ""}` : "Tap to refresh");

  return <button onClick={click} title={title} style={{
    position: "absolute", top: 12, right: 12, zIndex: 5,
    width: 30, height: 30, borderRadius: 15,
    background: "rgba(255,255,255,0.08)", border: "1px solid rgba(255,255,255,0.12)",
    color: "rgba(255,255,255,0.75)", cursor: "pointer",
    display: "flex", alignItems: "center", justifyContent: "center",
    fontSize: 16, lineHeight: 1, padding: 0,
  }}>
    <span style={{ display: "inline-block", animation: spinning ? "spin 0.8s linear infinite" : "none" }}>↻</span>
  </button>;
}

function Tab({ label, subtitle, active, onClick }) {
  return <button onClick={onClick} style={{
    flex: 1, padding: "12px 8px 10px", background: active ? C.card : "transparent",
    border: "none", borderBottom: active ? `3px solid ${C.acc}` : `3px solid transparent`,
    borderRadius: active ? "8px 8px 0 0" : 0,
    cursor: "pointer", textAlign: "center", transition: "background 0.15s",
  }}>
    <div style={{ fontSize: 15, fontWeight: 900, color: active ? C.w : C.dim, fontFamily: F, textTransform: "uppercase", letterSpacing: "0.05em" }}>{label}</div>
    {subtitle && <div style={{ fontSize: 11, color: active ? C.acc : C.dim, opacity: active ? 1 : 0.5, marginTop: 2, fontFamily: F }}>{subtitle}</div>}
  </button>;
}

// Identity claim — stored in localStorage so each device defaults to its owner.
// Returns [me, claim, ready]. Prompt fires once on first visit; never again on that device.
function useIdentity() {
  const [me, setMe] = useState(null);
  const [ready, setReady] = useState(false);
  useEffect(() => { loadData("me", null).then(v => { setMe(v); setReady(true); }); }, []);
  const claim = (u) => { setMe(u); saveData("me", u); };
  return [me, claim, ready];
}

function IdentityPrompt({ onClaim }) {
  return <div style={{ position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "rgba(0,0,0,0.8)", zIndex: 200, display: "flex", alignItems: "center", justifyContent: "center", backdropFilter: "blur(6px)", padding: 16 }}>
    <div style={{ width: "100%", maxWidth: 380, background: C.card, borderRadius: 16, padding: 20, border: `1px solid ${C.border}`, textAlign: "center" }}>
      <div style={{ fontSize: 28, marginBottom: 6 }}>🐶</div>
      <div style={{ fontSize: 20, fontWeight: 900, color: C.w, fontFamily: F, textTransform: "uppercase", letterSpacing: "0.04em", marginBottom: 4 }}>Who are you?</div>
      <div style={{ fontSize: 14, color: C.dim, marginBottom: 16, lineHeight: 1.5 }}>Picks lock the moment you cast them — so we need to know whose vote it is. Set once per device.</div>
      <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
        {USERS.map(u => <button key={u} onClick={() => onClaim(u)} style={{
          padding: "12px 16px", borderRadius: 10, border: `1px solid ${C.border}`,
          background: "rgba(59,157,255,0.06)", color: C.w, fontSize: 17, fontWeight: 700, fontFamily: F,
          cursor: "pointer", letterSpacing: "0.04em",
        }}>I'm {u}</button>)}
      </div>
    </div>
  </div>;
}

// "Voting as X — change" — slim text-link footer at the bottom of the expanded
// ladder panel. Identity is set once per device on first load, so this is a rarely-used
// escape hatch for when someone picks the wrong name on setup. Tap opens a confirmation
// modal before swapping device owner.
function SwitchIdentityLink({ me, onSwitch }) {
  const [showSwitch, setShowSwitch] = useState(false);
  return <>
    <button onClick={(e) => { e.stopPropagation(); setShowSwitch(true); }} style={{
      width: "100%", marginTop: 10, padding: "8px 10px", background: "transparent",
      border: "1px dashed rgba(255,255,255,0.12)", borderRadius: 8, cursor: "pointer",
      fontSize: 11, color: "rgba(255,255,255,0.5)", fontFamily: F, fontWeight: 700,
      textTransform: "uppercase", letterSpacing: "0.06em",
    }}>
      You're voting as <span style={{ color: C.w }}>{me}</span> · change
    </button>

    {showSwitch && <div onClick={() => setShowSwitch(false)} style={{ position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "rgba(0,0,0,0.7)", zIndex: 100, display: "flex", alignItems: "center", justifyContent: "center", backdropFilter: "blur(4px)", padding: 16 }}>
      <div onClick={(e) => e.stopPropagation()} style={{ width: "100%", maxWidth: 320, background: C.card, borderRadius: 14, padding: 18, border: `1px solid ${C.border}` }}>
        <div style={{ fontSize: 15, fontWeight: 800, color: C.w, fontFamily: F, textTransform: "uppercase", letterSpacing: "0.04em", marginBottom: 4, textAlign: "center" }}>Switch device owner?</div>
        <div style={{ fontSize: 13, color: C.dim, lineHeight: 1.5, marginBottom: 14, textAlign: "center" }}>Only do this if {me}'s phone is being shared. Their existing votes won't be changed.</div>
        <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
          {USERS.filter(u => u !== me).map(u => <button key={u} onClick={() => { onSwitch(u); setShowSwitch(false); }} style={{
            padding: "10px 14px", borderRadius: 8, border: `1px solid ${C.border}`,
            background: "rgba(59,157,255,0.06)", color: C.w, fontSize: 15, fontWeight: 700, fontFamily: F, cursor: "pointer",
          }}>Switch to {u}</button>)}
          <button onClick={() => setShowSwitch(false)} style={{ padding: "8px", borderRadius: 8, border: "none", background: "transparent", color: C.dim, fontSize: 14, fontFamily: F, fontWeight: 700, cursor: "pointer", textTransform: "uppercase", marginTop: 4 }}>cancel</button>
        </div>
      </div>
    </div>}
  </>;
}

// Official Bulldogs badge in the app header. Falls back to the dog emoji if the
// nrl.com SVG fails to load (e.g. CDN burp or theme key change).
function HeaderLogo() {
  const [failed, setFailed] = useState(false);
  if (failed || !MATCH.dogsLogo) return <span style={{ fontSize: 28, lineHeight: 1 }}>🐶</span>;
  return <img src={MATCH.dogsLogo} alt="Bulldogs" onError={() => setFailed(true)} style={{ width: 32, height: 32, objectFit: "contain", filter: "drop-shadow(0 2px 4px rgba(0,0,0,0.4))" }} />;
}

function TeamBadge({ src, fallback, name }) {
  const [failed, setFailed] = useState(false);
  if (failed || !src) return <div style={{ fontSize: 32, lineHeight: 1 }}>{fallback}</div>;
  return <img src={src} alt={name} onError={() => setFailed(true)} style={{ width: 56, height: 56, objectFit: "contain", filter: "drop-shadow(0 2px 6px rgba(0,0,0,0.4))" }} />;
}

function MiniBadge({ src, fallback }) {
  const [failed, setFailed] = useState(false);
  if (failed || !src) return <span style={{ fontSize: 15 }}>{fallback}</span>;
  return <img src={src} alt="" onError={() => setFailed(true)} style={{ width: 16, height: 16, objectFit: "contain" }} />;
}

function MatchHeader() {
  const dogsOdds = ODDS?.dogs != null ? `$${ODDS.dogs.toFixed(2)}` : null;
  const oppOdds = ODDS?.opp != null ? `$${ODDS.opp.toFixed(2)}` : null;
  return <div style={{ background: `linear-gradient(135deg, ${C.blue}, #002d6b)`, borderRadius: 14, padding: 18, textAlign: "center", marginBottom: 14, position: "relative", overflow: "hidden" }}>
    <div style={{ position: "absolute", top: -40, right: -40, width: 130, height: 130, borderRadius: "50%", background: "rgba(255,255,255,0.04)" }} />
    <div style={{ fontSize: 13, color: "rgba(255,255,255,0.5)", letterSpacing: "0.1em", textTransform: "uppercase", fontFamily: F, marginBottom: 6 }}>Round {MATCH.round} • {MATCH.kickoff}</div>
    <div style={{ display: "flex", justifyContent: "center", alignItems: "center", gap: 18 }}>
      <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 4 }}>
        <TeamBadge src={MATCH.dogsLogo} fallback="🐶" name="Bulldogs" />
        <div style={{ fontSize: 15, fontWeight: 900, color: C.w, fontFamily: F, letterSpacing: "0.04em" }}>DOGS</div>
        {dogsOdds && <div style={{ fontSize: 13, fontWeight: 800, color: C.wGold, fontFamily: F }}>{dogsOdds}</div>}
      </div>
      <div style={{ fontSize: 18, fontWeight: 900, color: "rgba(255,255,255,0.25)", fontFamily: F }}>{MATCH.dogsHome ? "v" : "@"}</div>
      <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 4 }}>
        <TeamBadge src={MATCH.oppLogo} fallback="🏉" name={MATCH.opponent} />
        <div style={{ fontSize: 15, fontWeight: 900, color: C.w, fontFamily: F, letterSpacing: "0.04em" }}>{MATCH.opponent.toUpperCase()}</div>
        {oppOdds && <div style={{ fontSize: 13, fontWeight: 800, color: C.wGold, fontFamily: F }}>{oppOdds}</div>}
      </div>
    </div>
    <div style={{ fontSize: 13, color: "rgba(255,255,255,0.5)", marginTop: 8 }}>📍 {MATCH.venue}</div>
  </div>;
}

// Tip — 5 margin-band pills with draft → confirm. Used on the This Week tab.
function TipCard({ me }) {
  const [tips, setTips] = useState({});
  const [draft, setDraft] = useState(null);

  useEffect(() => { loadData(`tips-r${MATCH.round}`, {}).then(setTips); }, []);
  useEffect(() => { if (Object.keys(tips).length) saveData(`tips-r${MATCH.round}`, tips); }, [tips]);

  const my = tips[me];
  const choose = (id) => { if (my) return; setDraft(id); };
  const lockIn = () => {
    if (my || !draft) return;
    setTips(p => ({ ...p, [me]: draft }));
    setDraft(null);
  };

  return <div style={{ background: C.card, borderRadius: 12, padding: 12, border: `1px solid ${C.border}`, marginBottom: 10 }}>
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
      <div style={{ fontSize: 15, fontWeight: 800, color: C.w, fontFamily: F, textTransform: "uppercase", letterSpacing: "0.04em" }}>🎯 Your tip</div>
      {my && <div style={{ fontSize: 12, color: C.grn, fontFamily: F, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em" }}>✓ Locked</div>}
    </div>
    <div style={{ display: "flex", gap: 4, marginBottom: draft ? 10 : 0 }}>
      {TIPS.map(opt => {
        const selected = (my || draft) === opt.id;
        const isLocked = my === opt.id;
        const others = USERS.filter(u => u !== me && tips[u] === opt.id);
        return <button key={opt.id} onClick={() => choose(opt.id)} style={{
          flex: 1, padding: "8px 2px", borderRadius: 8, cursor: my ? "default" : "pointer",
          border: selected ? `2px solid ${opt.color}` : `1px solid ${my ? "rgba(255,255,255,0.04)" : "rgba(255,255,255,0.1)"}`,
          background: selected ? opt.color + (isLocked ? "20" : "10") : "rgba(255,255,255,0.02)",
          color: selected ? opt.color : my ? "rgba(255,255,255,0.3)" : C.w,
          display: "flex", flexDirection: "column", alignItems: "center", gap: 2, position: "relative",
        }}>
          <span style={{ fontSize: 16 }}>{opt.emoji}</span>
          <span style={{ fontSize: 13, fontWeight: 700, fontFamily: F }}>{opt.short}</span>
          {(isLocked || others.length > 0) && <div style={{ position: "absolute", bottom: -7, left: 0, right: 0, display: "flex", gap: 2, justifyContent: "center" }}>
            {isLocked && <span style={{ fontSize: 11, fontWeight: 800, color: "#fff", background: opt.color, padding: "1px 4px", borderRadius: 3, fontFamily: F }}>{me[0]}</span>}
            {others.map(u => <span key={u} style={{ fontSize: 11, fontWeight: 800, color: C.dim, background: C.card, border: `1px solid ${C.border}`, padding: "1px 4px", borderRadius: 3, fontFamily: F }}>{u[0]}</span>)}
          </div>}
        </button>;
      })}
    </div>
    {draft && !my && <ConfirmBar
      label={`Lock in “${TIPS.find(t => t.id === draft)?.label}”`}
      hint="Tap another to change"
      color={TIPS.find(t => t.id === draft)?.color || C.acc}
      onConfirm={lockIn}
    />}
  </div>;
}

// Collapsible content section — used for supporting content (odds, kennel chatter,
// post-match reactions). Picks stay visible by default; only auxiliary stuff hides.
function Accordion({ icon, title, subtitle, color = C.acc, defaultOpen = false, children }) {
  const [open, setOpen] = useState(defaultOpen);
  return <div style={{ background: C.card, borderRadius: 12, marginBottom: 10, border: open ? `1px solid ${color}40` : `1px solid ${C.border}`, overflow: "hidden" }}>
    <button onClick={() => setOpen(!open)} style={{ width: "100%", padding: "12px 14px", background: "transparent", border: "none", cursor: "pointer", display: "flex", alignItems: "center", gap: 10, color: C.w, textAlign: "left" }}>
      <span style={{ fontSize: 18 }}>{icon}</span>
      <div style={{ flex: 1 }}>
        <div style={{ fontSize: 14, fontWeight: 800, fontFamily: F, textTransform: "uppercase", letterSpacing: "0.04em", color: open ? color : C.w }}>{title}</div>
        {subtitle && <div style={{ fontSize: 11, color: C.dim, marginTop: 1 }}>{subtitle}</div>}
      </div>
      <span style={{ fontSize: 16, color: open ? color : C.dim, transform: open ? "rotate(90deg)" : "rotate(0deg)", transition: "transform 0.2s" }}>▸</span>
    </button>
    {open && <div style={{ padding: "0 14px 14px", borderTop: `1px solid ${C.border}` }}>{children}</div>}
  </div>;
}

// "Hottest threads" list — Claude classifies threads per-tab so This Week shows
// upcoming-match chatter and Last Game shows fallout from the previous round.
// Each entry has a 1-2 sentence summary of what's actually being argued.
function KennelThreadsList({ threads = [] }) {
  if (!threads.length) return null;
  const prefixColor = { GAMEDAY: C.red, Opinion: C.gold, Official: C.acc, News: C.grn, "Social Media": C.purp };
  return <div style={{ marginTop: 12, marginBottom: 10 }}>
    <div style={{ fontSize: 11, fontWeight: 800, color: C.dim, fontFamily: F, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 6 }}>🔥 Hottest threads</div>
    {threads.map((t, i) => {
      const color = prefixColor[t.prefix] || C.dim;
      return <ExtLink key={i} href={t.url} style={{
        display: "block", padding: "8px 10px", borderRadius: 8,
        background: "rgba(0,0,0,0.25)", border: `1px solid ${C.border}`, marginBottom: 5, textDecoration: "none",
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: t.summary ? 4 : 0 }}>
          {t.prefix && <span style={{ fontSize: 10, fontWeight: 800, color, background: color + "20", padding: "2px 5px", borderRadius: 3, fontFamily: F, border: `1px solid ${color}40`, letterSpacing: "0.05em", flexShrink: 0 }}>{t.prefix.toUpperCase()}</span>}
          <span style={{ flex: 1, fontSize: 13, color: C.w, fontWeight: 700, lineHeight: 1.3 }}>{t.title}</span>
          <span style={{ fontSize: 11, color: C.dim, fontFamily: F, fontWeight: 700, whiteSpace: "nowrap" }}>{t.replies}↗</span>
        </div>
        {t.summary && <div style={{ fontSize: 12, color: "rgba(255,255,255,0.65)", lineHeight: 1.4 }}>{t.summary}</div>}
      </ExtLink>;
    })}
  </div>;
}

// Section header used to break tabs into named blocks.
function SectionHeader({ title, subtitle }) {
  return <div style={{ marginTop: 14, marginBottom: 8 }}>
    <div style={{ fontSize: 15, fontWeight: 800, color: C.w, fontFamily: F, textTransform: "uppercase", letterSpacing: "0.04em" }}>{title}</div>
    {subtitle && <div style={{ fontSize: 13, color: C.dim, lineHeight: 1.4, marginTop: 2 }}>{subtitle}</div>}
  </div>;
}

// Reusable confirm strip — used by tip, trivia, and each coaching decision so a stray
// tap never locks anyone in. Draft → tap "Lock it in" → committed.
function ConfirmBar({ label, hint, color, onConfirm }) {
  return <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
    <button onClick={onConfirm} style={{
      flex: 1, padding: "10px 14px", borderRadius: 8, border: "none", cursor: "pointer",
      background: color, color: "#fff", fontSize: 14, fontWeight: 800, fontFamily: F,
      textTransform: "uppercase", letterSpacing: "0.04em",
    }}>✓ {label}</button>
    {hint && <span style={{ fontSize: 11, color: C.dim, fontFamily: F, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.04em", flexShrink: 0 }}>{hint}</span>}
  </div>;
}

// Generic self-graded multi-choice card — used by trivia (one per round) and recap
// questions about last week (two per round). Persists picks under `picks-r{round}-{kind}`
// and the boolean grade under `grade-r{round}-{kind}` so the Parkyard Cup can tally
// without waiting for a post-match resolution feed.
function QuizCard({ me, q, qIdx, kind, accentColor, headerLabel, headerIcon }) {
  if (!q?.question) return null;
  const picksKey = `${kind}-r${MATCH.round}`;
  const gradeKey = `${kind}Grade-r${MATCH.round}`;
  const [picks, setPicks] = useState({});
  const [draft, setDraft] = useState(null);

  useEffect(() => { loadData(picksKey, {}).then(setPicks); }, [picksKey]);
  useEffect(() => { if (Object.keys(picks).length) saveData(picksKey, picks); }, [picks, picksKey]);

  // Picks are stored either as `{ user: idx }` (single question, e.g. trivia) or
  // `{ user: { qIdx: idx } }` (multi-question, e.g. recap). qIdx tells us which.
  const my = qIdx == null ? picks[me] : picks[me]?.[qIdx];
  const locked = my != null;
  const choose = (i) => { if (locked) return; setDraft(i); };
  const correct = q.correctIndex;
  const lockIn = async () => {
    if (locked || draft == null) return;
    setPicks(p => qIdx == null
      ? { ...p, [me]: draft }
      : { ...p, [me]: { ...(p[me] || {}), [qIdx]: draft } });
    const grade = await loadData(gradeKey, {});
    const next = qIdx == null
      ? { ...grade, [me]: draft === correct }
      : { ...grade, [me]: { ...(grade[me] || {}), [qIdx]: draft === correct } };
    saveData(gradeKey, next);
    setDraft(null);
  };

  const isRight = locked && my === correct;
  const otherPickFor = (i, u) => qIdx == null ? picks[u] === i : picks[u]?.[qIdx] === i;

  return <div style={{ background: `linear-gradient(135deg, ${accentColor}14, ${accentColor}03)`, borderRadius: 12, padding: 14, border: `1px solid ${accentColor}40`, marginBottom: 10 }}>
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
      <div style={{ fontSize: 15, fontWeight: 800, color: accentColor, fontFamily: F, textTransform: "uppercase", letterSpacing: "0.04em" }}>{headerIcon} {headerLabel}</div>
      {locked && <div style={{ fontSize: 12, fontFamily: F, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.05em", color: isRight ? C.grn : C.red }}>
        {isRight ? "✓ Correct" : "✗ Wrong"}
      </div>}
    </div>
    <div style={{ fontSize: 15, color: C.w, lineHeight: 1.4, marginBottom: 10, fontWeight: 600 }}>{q.question}</div>
    <div style={{ display: "flex", flexDirection: "column", gap: 6, marginBottom: locked || draft != null ? 10 : 0 }}>
      {q.options.map((opt, i) => {
        const selected = (locked ? my : draft) === i;
        const showCorrect = locked && i === correct;
        const showWrong = locked && selected && !isRight;
        const others = USERS.filter(u => u !== me && otherPickFor(i, u));
        const accent = showCorrect ? C.grn : showWrong ? C.red : selected ? accentColor : null;
        return <button key={i} onClick={() => choose(i)} style={{
          padding: "10px 14px", borderRadius: 10, cursor: locked ? "default" : "pointer", textAlign: "left",
          border: accent ? `2px solid ${accent}` : `1px solid ${locked ? "rgba(255,255,255,0.04)" : "rgba(255,255,255,0.1)"}`,
          background: accent ? accent + "14" : "rgba(255,255,255,0.02)",
          color: accent || (locked ? "rgba(255,255,255,0.3)" : C.w),
          fontSize: 15, fontWeight: 600,
          display: "flex", alignItems: "center", justifyContent: "space-between",
        }}>
          <span><span style={{ marginRight: 8 }}>{opt.emoji}</span>{opt.label}</span>
          <span style={{ display: "flex", gap: 6 }}>
            {locked && selected && <span style={{ fontSize: 13, fontWeight: 700, fontFamily: F }}>YOU</span>}
            {others.map(u => <span key={u} style={{ fontSize: 13, fontWeight: 700, color: C.dim, fontFamily: F }}>{u}</span>)}
          </span>
        </button>;
      })}
    </div>
    {!locked && draft != null && <ConfirmBar
      label="Lock in answer"
      hint="Tap another to change"
      color={accentColor}
      onConfirm={lockIn}
    />}
    {locked && q.explainer && <div style={{ fontSize: 13, color: C.dim, lineHeight: 1.5, marginTop: 4, fontStyle: "italic" }}>{q.explainer}</div>}
  </div>;
}

const TriviaCard = ({ me }) => <QuizCard me={me} q={TRIVIA} kind="trivia" accentColor={C.gold} headerLabel="Bulldogs trivia" headerIcon="🎓" />;

// Coach-decision cards (2 per round, sourced from Kennel chatter + the named 17).
// Lives inside the consolidated HaveYourSayPanel so it sits with the tip + trivia +
// recap picks. Pre-Tuesday (no team list yet) we show a "picks pending" placeholder.
function DebatesList({ me }) {
  const [picks, setPicks] = useState({});
  // One draft per debate id — separate from committed picks so a stray tap doesn't lock.
  const [drafts, setDrafts] = useState({});

  useEffect(() => { loadData(`debates-r${MATCH.round}`, {}).then(setPicks); }, []);
  useEffect(() => { if (Object.keys(picks).length) saveData(`debates-r${MATCH.round}`, picks); }, [picks]);

  const up = picks[me] || {};
  const choose = (id, label) => {
    if (up[id]) return;
    setDrafts(d => ({ ...d, [id]: label }));
  };
  const lockIn = (id) => {
    const d = drafts[id];
    if (!d || up[id]) return;
    setPicks(p => ({ ...p, [me]: { ...(p[me] || {}), [id]: d } }));
    setDrafts(prev => { const n = { ...prev }; delete n[id]; return n; });
  };

  if (DEBATES.length === 0) {
    return <div style={{ padding: "14px 12px", borderRadius: 10, border: `1px dashed ${C.border}`, background: "rgba(255,255,255,0.02)", textAlign: "center", marginBottom: 10 }}>
      <div style={{ fontSize: 22, marginBottom: 4 }}>📋</div>
      <div style={{ fontSize: 14, fontWeight: 700, color: C.w, fontFamily: F, textTransform: "uppercase", letterSpacing: "0.04em", marginBottom: 4 }}>Coaching picks unlock Tuesday</div>
      <div style={{ fontSize: 13, color: C.dim, lineHeight: 1.5 }}>NRL drops team lists Tuesday afternoon. The coach decisions get authored from the actual named 17 — refresh once you see the Dogs squad on nrl.com.</div>
    </div>;
  }

  return <>{DEBATES.map(d => {
    const picked = up[d.id];
    const draft = drafts[d.id];
    return <div key={d.id} style={{ background: C.card, borderRadius: 12, padding: 14, marginBottom: 10, border: `1px solid ${C.border}` }}>
      <div style={{ fontSize: 24, marginBottom: 6 }}>{d.icon}</div>
      <div style={{ fontSize: 16, fontWeight: 800, color: C.w, lineHeight: 1.3, marginBottom: 8 }}>{d.question}</div>
      {d.url
        ? <ExtLink href={d.url} style={{ display: "flex", alignItems: "flex-start", gap: 6, padding: "8px 10px", borderRadius: 8, background: "rgba(167,139,250,0.06)", border: `1px solid rgba(167,139,250,0.2)`, marginBottom: 10, textDecoration: "none" }}>
            <span style={{ fontSize: 15, flexShrink: 0 }}>🏟️</span>
            <span style={{ fontSize: 13, color: "#c4b5fd", lineHeight: 1.4, fontStyle: "italic", flex: 1 }}>{d.kennel}</span>
            <span style={{ fontSize: 13, color: "#c4b5fd", flexShrink: 0 }}>↗</span>
          </ExtLink>
        : <div style={{ display: "flex", alignItems: "flex-start", gap: 6, padding: "8px 10px", borderRadius: 8, background: "rgba(167,139,250,0.06)", border: `1px solid rgba(167,139,250,0.2)`, marginBottom: 10 }}>
            <span style={{ fontSize: 15, flexShrink: 0 }}>🏟️</span>
            <span style={{ fontSize: 13, color: "#c4b5fd", lineHeight: 1.4, fontStyle: "italic" }}>{d.kennel}</span>
          </div>}
      <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
        {d.options.map(opt => {
          const isLocked = picked === opt.label;
          const isDraft = !picked && draft === opt.label;
          const selected = isLocked || isDraft;
          const others = USERS.filter(u => u !== me && picks[u]?.[d.id] === opt.label);
          return <button key={opt.label} onClick={() => choose(d.id, opt.label)} style={{
            padding: "10px 14px", borderRadius: 10, cursor: picked ? "default" : "pointer",
            border: selected ? `2px solid ${C.acc}` : `1px solid ${picked ? "rgba(255,255,255,0.04)" : "rgba(255,255,255,0.1)"}`,
            background: selected ? `rgba(59,157,255,0.${isLocked ? "12" : "06"})` : "rgba(255,255,255,0.02)",
            color: selected ? C.acc : picked ? "rgba(255,255,255,0.3)" : C.w,
            fontSize: 15, fontWeight: 600, textAlign: "left",
            display: "flex", alignItems: "center", justifyContent: "space-between",
          }}>
            <span><span style={{ marginRight: 8 }}>{opt.emoji}</span>{opt.label}</span>
            <span style={{ display: "flex", gap: 4 }}>
              {isLocked && <span style={{ fontSize: 13, fontWeight: 700, color: C.acc, fontFamily: F }}>YOU</span>}
              {others.map(u => <span key={u} style={{ fontSize: 13, fontWeight: 700, color: C.dim, fontFamily: F }}>{u}</span>)}
            </span>
          </button>;
        })}
      </div>
      {!picked && draft && <div style={{ marginTop: 10 }}>
        <ConfirmBar label="Lock in pick" hint="Tap another to change" color={C.acc} onConfirm={() => lockIn(d.id)} />
      </div>}
    </div>;
  })}</>;
}

// Reads the current user's progress across all 4 pick types (tip, coach debates,
// recap, trivia) and exposes a live count. Re-fetches on the `picks-changed` event
// dispatched by storage.saveData, so the panel subtitle stays in sync as picks lock.
function usePicksCount(me) {
  const total = 1 + DEBATES.length + RECAPS.length + (TRIVIA?.question ? 1 : 0);
  const [count, setCount] = useState(0);

  useEffect(() => {
    if (!me) { setCount(0); return; }
    let cancelled = false;
    const refresh = async () => {
      const [tips, debates, recap, trivia] = await Promise.all([
        loadData(`tips-r${MATCH.round}`, {}),
        loadData(`debates-r${MATCH.round}`, {}),
        loadData(`recap-r${MATCH.round}`, {}),
        loadData(`trivia-r${MATCH.round}`, {}),
      ]);
      if (cancelled) return;
      const n = (tips[me] ? 1 : 0)
        + Object.keys(debates[me] || {}).length
        + Object.keys(recap[me] || {}).length
        + (trivia[me] != null ? 1 : 0);
      setCount(n);
    };
    refresh();
    window.addEventListener("dogs-hq:picks-changed", refresh);
    return () => { cancelled = true; window.removeEventListener("dogs-hq:picks-changed", refresh); };
  }, [me]);

  return { count, total };
}

// Consolidated picks panel — single collapsible strip that sits between the header
// band and the tab nav. Bundles tip + coach debates + recap + trivia into one place
// so picks aren't hidden behind two tabs.
function HaveYourSayPanel({ me }) {
  const [open, setOpen] = useState(false);
  const { count, total } = usePicksCount(me);
  const done = total > 0 && count >= total;

  return <div style={{ background: "rgba(0,0,0,0.28)", borderTop: "1px solid rgba(255,255,255,0.08)" }}>
    <button onClick={() => setOpen(!open)} style={{
      width: "100%", padding: "12px 14px", background: "transparent", border: "none", cursor: "pointer",
      display: "flex", alignItems: "center", gap: 10, color: C.w, textAlign: "left",
    }}>
      <span style={{ fontSize: 20 }}>🗣️</span>
      <div style={{ flex: 1 }}>
        <div style={{ fontSize: 15, fontWeight: 800, fontFamily: F, textTransform: "uppercase", letterSpacing: "0.06em", color: open ? C.wGold : C.w }}>Have your say</div>
        <div style={{ fontSize: 11, color: done ? C.grn : "rgba(255,255,255,0.55)", fontFamily: F, fontWeight: 700, marginTop: 2, textTransform: "uppercase", letterSpacing: "0.06em" }}>
          {done ? "All in ✓" : `${count}/${total} picked`}
        </div>
      </div>
      <span style={{ fontSize: 16, color: open ? C.wGold : "rgba(255,255,255,0.5)", transform: open ? "rotate(90deg)" : "rotate(0deg)", transition: "transform 0.2s" }}>▸</span>
    </button>
    {open && <div style={{ padding: "12px 14px 14px", background: C.dk, borderTop: "1px solid rgba(255,255,255,0.08)" }}>
      <TipCard me={me} />
      <DebatesList me={me} />
      {RECAPS.map((q, i) => <QuizCard key={i} me={me} q={q} qIdx={i} kind="recap" accentColor={C.acc} headerLabel="Recap" headerIcon="📼" />)}
      {TRIVIA?.question && <TriviaCard me={me} />}
    </div>}
  </div>;
}

// ── THIS WEEK TAB ──
// Forward-looking match context. Picks (tip + coach decisions) have moved up to the
// consolidated HaveYourSayPanel above the tab nav — this tab now just shows the
// match card and Kennel chatter for the upcoming game.
function ThisWeekTab() {
  return <div style={{ padding: 14 }}>
    <MatchHeader />

    {/* From The Kennel — top 3 upcoming-match threads + mood + 1 spicy quote. Open by default. */}
    <Accordion icon="🏟️" title="From The Kennel" subtitle={KENNEL_TIP_LEAN.confidence} color={C.purp} defaultOpen={true}>
      <div style={{ fontSize: 14, color: C.w, lineHeight: 1.5, fontStyle: "italic", marginTop: 10 }}>{KENNEL_TIP_LEAN.note}</div>
      <KennelThreadsList threads={data.kennelThreadsThisWeek || []} />
      {KENNEL_TIP_QUOTES?.[0] && <div style={{ padding: "8px 10px", borderRadius: 8, background: "rgba(0,0,0,0.25)", borderLeft: `2px solid rgba(167,139,250,0.5)` }}>
        <div style={{ fontSize: 14, color: C.w, lineHeight: 1.4, marginBottom: 3 }}>"{KENNEL_TIP_QUOTES[0].quote}"</div>
        {KENNEL_TIP_QUOTES[0].url
          ? <ExtLink href={KENNEL_TIP_QUOTES[0].url} style={{ fontSize: 12, color: C.purp, fontFamily: F, textDecoration: "none" }}>— {KENNEL_TIP_QUOTES[0].thread} ↗</ExtLink>
          : <div style={{ fontSize: 12, color: C.dim, fontFamily: F }}>— {KENNEL_TIP_QUOTES[0].thread}</div>}
      </div>}
    </Accordion>
  </div>;
}

// ── LAST GAME TAB ──
// Retrospective match context. Recap + trivia picks have moved up to the
// consolidated HaveYourSayPanel above the tab nav — this tab now just shows the
// score banner, headline/vibe, and post-match Kennel reactions.
function LastGameTab() {
  const w = WASHUP;
  if (!w) return <div style={{ padding: 24, textAlign: "center", color: C.dim, fontSize: 15 }}>No last game yet — first match of the season hasn't been played.</div>;

  const isWin = w.result === "WIN";
  const accent = isWin ? C.grn : (w.result === "DRAW" ? C.gold : C.red);

  return <div style={{ padding: 14 }}>
    {/* Score banner with logos */}
    <div style={{ background: `${accent}14`, borderRadius: 14, padding: 18, border: `1px solid ${accent}40`, marginBottom: 14 }}>
      <div style={{ fontSize: 13, color: C.dim, fontFamily: F, textTransform: "uppercase", letterSpacing: "0.1em", textAlign: "center", marginBottom: 8 }}>Round {w.round} • Dogs {w.dogsHome ? "v" : "@"} {w.opponent}</div>
      <div style={{ display: "flex", justifyContent: "center", alignItems: "center", gap: 14 }}>
        <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 4 }}>
          <TeamBadge src={w.dogsLogo} fallback="🐶" name="Dogs" />
          <span style={{ fontSize: 32, fontWeight: 900, color: isWin ? accent : C.dim, fontFamily: F, lineHeight: 1 }}>{w.dogsScore}</span>
        </div>
        <span style={{ fontSize: 16, color: C.dim, fontWeight: 700 }}>–</span>
        <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 4 }}>
          <TeamBadge src={w.oppLogo} fallback="🏉" name={w.opponent} />
          <span style={{ fontSize: 32, fontWeight: 900, color: !isWin ? accent : C.dim, fontFamily: F, lineHeight: 1 }}>{w.oppScore}</span>
        </div>
      </div>
      <div style={{ textAlign: "center", marginTop: 10 }}>
        <span style={{ display: "inline-block", padding: "3px 14px", borderRadius: 16, background: `${accent}28`, color: accent, fontWeight: 800, fontSize: 15, fontFamily: F, textTransform: "uppercase" }}>
          {w.result} by {Math.abs(w.margin)} {isWin ? "🐶" : "💀"}
        </span>
      </div>
    </div>

    {/* Headline + vibe */}
    {w.headline && <div style={{ fontSize: 18, fontWeight: 800, color: C.w, marginBottom: 6, lineHeight: 1.3 }}>{w.headline}</div>}
    {w.vibe && <div style={{ fontSize: 15, color: C.dim, lineHeight: 1.6, marginBottom: 16 }}>{w.vibe}</div>}

    {/* Kennel post-match — open by default. Top 3 threads + mood summary + 1 hot take. */}
    {(w.kennelMood || w.kennelSummary) && <Accordion icon="🏟️" title="From The Kennel" subtitle={w.kennelMood ? `Mood: ${w.kennelMood}` : "Post-match reactions"} color={C.purp} defaultOpen={true}>
      {w.kennelSummary && <div style={{ fontSize: 14, color: C.w, lineHeight: 1.5, marginTop: 10, fontStyle: "italic" }}>{w.kennelSummary}</div>}
      <KennelThreadsList threads={data.kennelThreadsLastGame || []} />
      {w.kennelHotTakes?.[0] && <div style={{ padding: "8px 10px", borderRadius: 8, background: "rgba(0,0,0,0.25)", borderLeft: "2px solid rgba(167,139,250,0.5)" }}>
        <div style={{ fontSize: 14, color: C.w, lineHeight: 1.4 }}>"{w.kennelHotTakes[0].quote}"</div>
        <div style={{ fontSize: 12, color: C.dim, fontFamily: F, marginTop: 3, display: "flex", justifyContent: "space-between", alignItems: "center", gap: 6 }}>
          <span>{w.kennelHotTakes[0].author ? `— ${w.kennelHotTakes[0].author}` : ""}</span>
          {w.kennelHotTakes[0].url && <ExtLink href={w.kennelHotTakes[0].url} style={{ color: C.purp, textDecoration: "none", fontWeight: 700 }}>view thread ↗</ExtLink>}
        </div>
      </div>}
      {w.gamedayUrl && <ExtLink href={w.gamedayUrl} style={{ display: "block", marginTop: 10, fontSize: 13, color: C.purp, fontFamily: F, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.04em", textAlign: "center", textDecoration: "none" }}>read the gameday thread ↗</ExtLink>}
    </Accordion>}
  </div>;
}

// ── LADDER (embedded in the app header, collapsed by default) ──
// One-line strip with each user's running total + crown for leader. Tap to expand
// into the per-pick breakdown. Tipping + coach grading still wait on the post-match
// resolution feed (empty for now), but trivia + recap self-grade on lock.
function LadderHeader({ me, onSwitch }) {
  const [tipsByRound, setTipsByRound] = useState({});
  const [coachByRound, setCoachByRound] = useState({});
  const [triviaByRound, setTriviaByRound] = useState({});
  const [triviaGradeByRound, setTriviaGradeByRound] = useState({});
  const [recapByRound, setRecapByRound] = useState({});
  const [recapGradeByRound, setRecapGradeByRound] = useState({});

  // data.resolutions accumulates per-round tipBand + debateVerdicts across the
  // season — generate.js merges in a fresh entry every time it sees a new
  // prevMatch. Shape: { [round]: { tipBand, debateVerdicts: { [id]: label } } }.
  const resolutionsByRound = data.resolutions || {};
  const resolutions = Object.entries(resolutionsByRound).map(([round, r]) => ({
    round: Number(round),
    tipBand: r.tipBand,
    debateVerdicts: r.debateVerdicts || {},
  }));

  useEffect(() => {
    (async () => {
      // Load every round we might have picks for: anything resolved + the upcoming match
      // + the washup round (which may not be in resolutions yet on a freshly-played weekend).
      const rounds = [...new Set([
        WASHUP?.round,
        MATCH.round,
        ...Object.keys(resolutionsByRound).map(Number),
      ].filter(Boolean))];
      const t = {}, c = {}, tr = {}, tg = {}, rc = {}, rg = {};
      for (const r of rounds) {
        t[r] = await loadData(`tips-r${r}`, {});
        c[r] = await loadData(`debates-r${r}`, {});
        tr[r] = await loadData(`trivia-r${r}`, {});
        tg[r] = await loadData(`triviaGrade-r${r}`, {});
        rc[r] = await loadData(`recap-r${r}`, {});
        rg[r] = await loadData(`recapGrade-r${r}`, {});
      }
      setTipsByRound(t);
      setCoachByRound(c);
      setTriviaByRound(tr);
      setTriviaGradeByRound(tg);
      setRecapByRound(rc);
      setRecapGradeByRound(rg);
    })();
  }, []);

  const totals = USERS.map(u => {
    let tips = 0, tipsCorrect = 0, coach = 0, coachCorrect = 0, trivia = 0, triviaCorrect = 0, recap = 0, recapCorrect = 0;
    for (const r of resolutions) {
      const myTip = tipsByRound[r.round]?.[u];
      if (myTip) { tips++; if (myTip === r.tipBand) tipsCorrect++; }
      const myDebates = coachByRound[r.round]?.[u] || {};
      for (const [id, pick] of Object.entries(myDebates)) {
        coach++; if (pick === r.debateVerdicts?.[id]) coachCorrect++;
      }
    }
    // Trivia + recap are graded immediately at lock time — independent of post-match resolutions.
    for (const grade of Object.values(triviaGradeByRound)) {
      if (grade?.[u] != null) { trivia++; if (grade[u]) triviaCorrect++; }
    }
    for (const grade of Object.values(recapGradeByRound)) {
      for (const v of Object.values(grade?.[u] || {})) { recap++; if (v) recapCorrect++; }
    }
    return { user: u, tips, tipsCorrect, coach, coachCorrect, trivia, triviaCorrect, recap, recapCorrect, score: tipsCorrect + coachCorrect + triviaCorrect + recapCorrect };
  });
  const sorted = [...totals].sort((a, b) => b.score - a.score);
  const anyScored = totals.some(t => t.trivia > 0 || t.recap > 0) || resolutions.length > 0;

  const [open, setOpen] = useState(false);
  const leader = sorted[0]?.score > 0 ? sorted[0] : null;

  return <>
    {/* Trophy toggle — small circular button at top-left of the header band, mirroring
        the refresh button on the right. Replaces the old full-width strip; the standings
        only render inline below when expanded. Gold ring when the current user is leading. */}
    <button onClick={() => setOpen(!open)} title="Parkyard Cup standings" style={{
      position: "absolute", top: 12, left: 12, zIndex: 5,
      width: 30, height: 30, borderRadius: 15,
      background: open ? "rgba(251,191,36,0.18)" : "rgba(255,255,255,0.08)",
      border: `1px solid ${open ? "rgba(251,191,36,0.45)" : "rgba(255,255,255,0.12)"}`,
      cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center",
      fontSize: 16, lineHeight: 1, padding: 0,
    }}>
      <span>🏆</span>
      {leader?.user === me && <span style={{ position: "absolute", top: -3, right: -3, fontSize: 11 }}>👑</span>}
    </button>

    {open && <div style={{ padding: "8px 12px 14px", background: "rgba(0,0,0,0.22)", borderTop: "1px solid rgba(255,255,255,0.06)" }}>
      <div style={{ fontSize: 11, fontWeight: 800, color: C.wGold, fontFamily: F, textTransform: "uppercase", letterSpacing: "0.12em", textAlign: "center", marginBottom: 8, marginTop: 2 }}>
        🏆 Parkyard Cup · 2026 Season
      </div>
      {!anyScored ? (
        <div style={{ padding: "16px 12px", textAlign: "center", borderRadius: 10, background: "rgba(255,255,255,0.03)", border: "1px dashed rgba(255,255,255,0.1)" }}>
          <div style={{ fontSize: 22, marginBottom: 4 }}>🏁</div>
          <div style={{ fontSize: 14, color: C.w, fontWeight: 700, fontFamily: F, marginBottom: 4 }}>Off and racing.</div>
          <div style={{ fontSize: 12, color: "rgba(255,255,255,0.6)", lineHeight: 1.5 }}>Lock trivia or recap for instant points. Tip + coach settle after full-time.</div>
        </div>
      ) : <>
        {/* Column headers — matches the NRL ladder feel: POS / USER / per-pick / PTS */}
        <div style={{
          display: "grid", gridTemplateColumns: "22px 1fr 30px 30px 30px 30px 38px",
          gap: 8, alignItems: "center", padding: "6px 8px",
          fontSize: 10, fontWeight: 800, color: "rgba(255,255,255,0.45)",
          fontFamily: F, textTransform: "uppercase", letterSpacing: "0.08em",
          borderBottom: "1px solid rgba(255,255,255,0.1)",
        }}>
          <span></span>
          <span>User</span>
          <span style={{ textAlign: "center" }}>🎯</span>
          <span style={{ textAlign: "center" }}>📼</span>
          <span style={{ textAlign: "center" }}>🎓</span>
          <span style={{ textAlign: "center" }}>🧠</span>
          <span style={{ textAlign: "right" }}>Pts</span>
        </div>
        {sorted.map((row, idx) => {
          const isLeader = idx === 0 && row.score > 0;
          return <div key={row.user} style={{
            display: "grid", gridTemplateColumns: "22px 1fr 30px 30px 30px 30px 38px",
            gap: 8, alignItems: "center", padding: "10px 8px",
            background: isLeader
              ? `linear-gradient(90deg, rgba(251,191,36,0.18), rgba(251,191,36,0.04) 80%)`
              : idx % 2 === 0 ? "rgba(255,255,255,0.02)" : "transparent",
            borderRadius: 6,
            borderLeft: isLeader ? `3px solid ${C.wGold}` : "3px solid transparent",
            marginTop: 2,
          }}>
            <span style={{ fontSize: 18, fontWeight: 900, color: isLeader ? C.wGold : "rgba(255,255,255,0.45)", fontFamily: F }}>{idx + 1}</span>
            <span style={{ fontSize: 16, fontWeight: 800, color: C.w, fontFamily: F, display: "flex", alignItems: "center", gap: 6 }}>
              {row.user}
              {isLeader && <span style={{ fontSize: 14 }} title="Leader">👑</span>}
            </span>
            <span style={{ textAlign: "center", fontSize: 15, fontWeight: 800, color: row.tipsCorrect > 0 ? C.acc : "rgba(255,255,255,0.25)", fontFamily: F }}>{row.tipsCorrect}</span>
            <span style={{ textAlign: "center", fontSize: 15, fontWeight: 800, color: row.recapCorrect > 0 ? C.acc : "rgba(255,255,255,0.25)", fontFamily: F }}>{row.recapCorrect}</span>
            <span style={{ textAlign: "center", fontSize: 15, fontWeight: 800, color: row.triviaCorrect > 0 ? C.gold : "rgba(255,255,255,0.25)", fontFamily: F }}>{row.triviaCorrect}</span>
            <span style={{ textAlign: "center", fontSize: 15, fontWeight: 800, color: row.coachCorrect > 0 ? C.purp : "rgba(255,255,255,0.25)", fontFamily: F }}>{row.coachCorrect}</span>
            <span style={{ textAlign: "right", fontSize: 22, fontWeight: 900, color: isLeader ? C.wGold : C.w, fontFamily: F, lineHeight: 1 }}>{row.score}</span>
          </div>;
        })}
      </>}
      {me && <SwitchIdentityLink me={me} onSwitch={onSwitch} />}
    </div>}
  </>;
}

// ── APP ──
export default function DogsHQ() {
  const [tab, setTab] = useState("this_week");
  const [me, claim, ready] = useIdentity();

  // Fire-and-forget auto-regen check on first mount. Server decides if a
  // refresh window has passed (post-match, team-list day) and kicks off the
  // pipeline silently. This visitor keeps their current view; next page load
  // gets fresh content. Manual button (Tony) is the in-session escape hatch.
  useEffect(() => {
    fetch("/api/check-stale").catch(() => {});
  }, []);

  if (!ready) return <div style={{ minHeight: "100vh", background: C.dk }} />;

  // Tab subtitles read straight from data so the bottom nav always reflects the round.
  const thisWeekSub = `Rd ${MATCH.round} v ${MATCH.opponent}`;
  const lastGameSub = WASHUP ? `${WASHUP.dogsScore}-${WASHUP.oppScore} v ${WASHUP.opponent}` : "—";

  return <div style={{ maxWidth: 480, margin: "0 auto", minHeight: "100vh", background: C.dk, color: C.w, fontFamily: "'Inter', -apple-system, sans-serif" }}>
    {/* App header: title (with official Bulldogs badge) + ladder strip + voter line.
        All three layers share the same dark band so they read as one unit. */}
    <div style={{ background: `linear-gradient(180deg, ${C.blue}, ${C.blue}dd 50%, ${C.dk} 100%)`, position: "relative" }}>
      <RefreshButton me={me} />
      <div style={{ padding: "14px 14px 4px", textAlign: "center" }}>
        <div style={{ display: "inline-flex", alignItems: "center", gap: 10 }}>
          <HeaderLogo />
          <div style={{ fontSize: 24, fontWeight: 900, fontFamily: F, color: C.w, letterSpacing: "0.04em", textTransform: "uppercase" }}>Dog Yard</div>
        </div>
      </div>
      <LadderHeader me={me} onSwitch={claim} />
      {me && <HaveYourSayPanel me={me} />}
    </div>

    {/* Tab nav — sticky two-tab with subtitle showing the round/last result */}
    <div style={{ display: "flex", background: C.dk, position: "sticky", top: 0, zIndex: 10, padding: "0 14px", borderBottom: `1px solid ${C.border}` }}>
      <Tab label="This Week" subtitle={thisWeekSub} active={tab === "this_week"} onClick={() => setTab("this_week")} />
      <Tab label="Last Game" subtitle={lastGameSub} active={tab === "last_game"} onClick={() => setTab("last_game")} />
    </div>

    {me && <div style={{ paddingBottom: 40 }}>
      {tab === "this_week" && <ThisWeekTab />}
      {tab === "last_game" && <LastGameTab />}
    </div>}

    {!me && <IdentityPrompt onClaim={claim} />}
  </div>;
}
